DROP DATABASE IF EXISTS OddChopStix_db;

CREATE DATABASE OddChopStix_db;

USE OddChopStix_db;

CREATE TABLE foods(
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
	food_name VARCHAR(50) NOT NULL,
	food_photo LONGBLOB,
	food_description VARCHAR(500) NOT NULL,
	PRIMARY KEY(id)

);

CREATE TABLE alcohols(
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
	alc_name VARCHAR(50) NOT NULL,
	alc_photo LONGBLOB,
	alc_description VARCHAR(500) NOT NULL,
	PRIMARY KEY(id)

);

CREATE TABLE pairings(
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
	alc_id INTEGER(11) NOT NULL,
	food_id INTEGER(11) NOT NULL,
	rating INTEGER(1) NOT NULL,
	review VARCHAR(500),
	review_date TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY(id)

);